function getInfoBasedOnScore(totalScore) {

    // Função que retorna informações baseadas na pontuação total.
    if (totalScore >= 20) {
        // Se a pontuação total for maior ou igual a 20.
        console.log('Chegou aqui', totalScore)

        document.getElementById('printtotalscore').innerHTML = '<h1 class="print-result">Nível <span>Altíssimo</span></h1>'

        document.getElementById('printresultquest').innerHTML = '<h2 class ="result-title">Sua procrastinação está <span>alta</span>? Vamos ver as causas da procrastinação!</h2><p class="result-text">Compreender por que você ou alguém em sua equipe está procrastinando é o primeiro passo para enfrentar esse comportamento!</p><h2 class="result-title-dica">Veja quais são os principais motivos que levam uma pessoa a procrastinar:</h2><h2 class="result-title">Falta de <span>Prioritização</span></h2><p class="result-text">Um dos principais motivos para a procrastinação é a falta de priorização. Esse problema pode ser mais amplo do que pessoal. <br> <br> Em uma empresa, isso pode ocorrer quando as metas, os objetivos e os prazos não estão claramente definidos. A ausência de uma pessoa responsável por determinada tarefa também pode contribuir para a procrastinação. <br> <br> No âmbito pessoal, uma pessoa que não se organiza adequadamente, não compreende os prazos ou a importância das tarefas pode acabar se perdendo na priorização e achar que é aceitável adiar suas responsabilidades.</p><h2 class="result-title">Medo do <span>Erro</span></h2><p class="result-text">Outro motivo para a procrastinação é o medo de cometer erros. Esse medo é mais comum em tarefas importantes e desafiadoras. <br> <br> Esse problema pode surgir em um ambiente corporativo que não promove uma cultura de feedback, não oferece capacitações eficazes, pratica microgerenciamento ou não mantém um ambiente seguro para que os colaboradores possam errar e aprender.</p><h2 class="result-title">Falta de <span>Incentivo</span></h2><p class="result-text">Esse motivo está relacionado ao anterior. O medo de errar muitas vezes está associado à ideia de punição por tarefas mal realizadas. <br> <br> Se uma empresa cria incentivos ou oferece feedbacks positivos publicamente quando uma tarefa é concluída dentro do prazo, isso pode aumentar a motivação da pessoa e ajudar a reduzir a procrastinação.</p>'

        document.getElementById('printresultquest2').innerHTML = '<h2 class="result-title">Problemas <span>Físicos</span> ou <span>Emocionais</span></h2><p class="result-text">A procrastinação pode ser um problema crônico, resultante de questões emocionais ou físicas. <br> <br> Problemas emocionais, como luto ou situações familiares adversas, podem contribuir para a procrastinação. Nesses casos, o acompanhamento psicológico pode ser necessário. <br> <br> Para problemas físicos, a causa pode ser mais complexa, envolvendo condições neurológicas, como má formação cerebral ou lesões no córtex pré-frontal, região responsável pelo foco e concentração. <br> <br> Além disso, a procrastinação pode ser um indicativo de burnout, o que requer atenção tanto para causas físicas quanto emocionais. <br> <br> É importante considerar que as pessoas que procrastinam muitas vezes não sabem exatamente por que agem dessa forma. Em muitos casos, é uma combinação de fatores como falta de motivação, baixa energia, ansiedade, falta de preparo e, ocasionalmente, preguiça.</p> <h2 class="result-title-dica">Indicações de <span>livros</span> sobre procrastinação!</h2><h2 class="result-title-italic">Arrume a Sua Cama: Pequenas Coisas que Podem Mudar a Sua Vida… E Talvez o Mundo</h2><p class="result-text">O almirante William H. McRaven mostra em sua obra como um simples hábito cultivado diariamente pode representar uma grande vitória.</p> <br> <br> <p class="result-text">Na verdade, o livro é uma transcrição e extensão do célebre discurso que ele fez para uma aula inaugural na Universidade de Austin, no Texas, que você pode conferir no vídeo abaixo: <br> <br>Assistir no YouTube:  <a class="link" target="_blank" href="https://www.youtube.com/watch?v=IlGEGEm1_5k">https://www.youtube.com/watch?v=IlGEGEm1_5k</a></p> <br> <br> <h2 class="result-title-italic">A Procrastinação: Aprendendo a Lidar com Ela</h2><p class="result-text">Jane B. Burka e Lenora M. Yuen, duas psicólogas clínicas, oferecem uma visão abrangente sobre a procrastinação. Elas exploram os fatores emocionais e cognitivos envolvidos no comportamento procrastinador e ensinam técnicas e exercícios para superar esse padrão.</p> <br> <br> <h2 class="result-title-italic">O Poder do Hábito</h2><p class="result-text">Embora este livro não seja especificamente sobre procrastinação, ele aborda o tema dos hábitos e como eles influenciam nosso comportamento.</p>'

        var score_info = "Nível Altíssimo"
        var result_quest = '<h1 class="print-result">Nível <span>Intermediário</span></h1>'
    } else if (totalScore >= 11) {
        document.getElementById('txtUsuario')
        // Se a pontuação total for entre 11 e 19.
        console.log('Chegou aqui', totalScore)

        document.getElementById('printtotalscore').innerHTML = '<h1 class="print-result">Nível <span>Intermediário</span></h1>'

        document.getElementById('printresultquest').innerHTML = '<h2 class="result-title">Procrastinador <span>Relaxado</span></h2><p class="result-text">O procrastinador relaxado é aquele que, ao adiar uma tarefa, opta por fazer algo mais agradável. Ele reconhece que a tarefa evitada é desagradável, mas não se sente culpado por isso e nem se preocupa em lidar rapidamente com as consequências. Esse tipo de procrastinador prefere deixar o tempo passar sem se estressar.</p> <h2 class="result-title">Procrastinador <span>Tenso</span></h2> <p class="result-text">Por outro lado, o procrastinador tenso sabe que deveria realizar a atividade, mas não consegue encontrar motivação suficiente para iniciar. Mesmo procrastinando, ele sente culpa e tensão constantes por não estar se dedicando à tarefa. Essa culpa pode aumentar a ansiedade, criando um ciclo de procrastinação difícil de quebrar.</p><h2 class="result-title-dica">Dicas para <span>ajudar</span> com a <span>procrastinação!</span></h2><h2 class="result-title">Dê pequenos primeiros <span>passos.</span></h2><p class="result-text-dica">Iniciar com um pequeno movimento é uma estratégia respaldada pela ciência para superar a procrastinação. A ideia é estabelecer uma meta tão pequena que, “o hedonista em você, que prefere o prazer imediato e adiar as responsabilidades, não conseguirá recusar”.<br> <br>O psicólogo Tim Pychyl, diretor do Centro de Pesquisa sobre Procrastinação da Universidade de Carleton, no Canadá, testou essa abordagem. Seus resultados confirmaram a eficácia: “Uma vez que os alunos começaram, eles avaliaram as tarefas como menos difíceis e estressantes, além de mais agradáveis do que imaginavam”.</p><h2 class="result-title"><span>Estabeleça</span> horários para tudo.</h2><p class="result-text-dica">Definir horários é uma estratégia eficaz para combater a procrastinação ao criar uma programação para o dia. Você saberá exatamente quais tarefas devem ser realizadas em momentos específicos, evitando a sensação de sobrecarga e desordem.<br> <br>Além disso, estabelecer horários cria um senso de responsabilidade e compromisso. Quando você define um horário para uma tarefa, está criando um compromisso consigo mesmo para realizá-la naquele período determinado.<br> <br>Isso aumenta a motivação e a disciplina, tornando provável que você realmente inicie e conclua as tarefas no tempo estipulado.</p>'

        var score_info = '<h1 class="print-result">Nível <span>Intermediário</span></h1>'
        var result_quest = '<h2 class="result-title">Procrastinador <span>Relaxado</span></h2><p class="result-text">O procrastinador relaxado é aquele que, ao adiar uma tarefa, opta por fazer algo mais agradável. Ele reconhece que a tarefa evitada é desagradável, mas não se sente culpado por isso e nem se preocupa em lidar rapidamente com as consequências. Esse tipo de procrastinador prefere deixar o tempo passar sem se estressar.</p> <h2 class="result-title">Procrastinador <span>Tenso</span></h2> <p class="result-text">Por outro lado, o procrastinador tenso sabe que deveria realizar a atividade, mas não consegue encontrar motivação suficiente para iniciar. Mesmo procrastinando, ele sente culpa e tensão constantes por não estar se dedicando à tarefa. Essa culpa pode aumentar a ansiedade, criando um ciclo de procrastinação difícil de quebrar.</p><h2 class="result-title-dica">Dicas para <span>ajudar</span> com a <span>procrastinação</span></h2><h2 class="result-title">Dê pequenos primeiros <span>passo</span></h2><p class="result-text-dica"> Iniciar com um pequeno movimento é uma estratégia respaldada pela ciência para superar a procrastinação. A ideia é estabelecer uma meta tão pequena que, “o hedonista em você, que prefere o prazer imediato e adiar as responsabilidades, não conseguirá recusar”.<br> <br>O psicólogo Tim Pychyl, diretor do Centro de Pesquisa sobre Procrastinação da Universidade de Carleton, no Canadá, testou essa abordagem. Seus resultados confirmaram a eficácia: “Uma vez que os alunos começaram, eles avaliaram as tarefas como menos difíceis e estressantes, além de mais agradáveis do que imaginavam”.</p><h2 class="result-title"><span>Estabeleça</span> horários para tudo</h2><p class="result-text-dica">Definir horários é uma estratégia eficaz para combater a procrastinação, pois cria uma programação para o dia. Você saberá exatamente quais tarefas devem ser realizadas em momentos específicos, o que evita a sensação de sobrecarga e desordem. <br> <br> Além disso, estabelecer horários cria um senso de responsabilidade e compromisso. Quando você define um horário para uma tarefa, está criando um compromisso consigo mesmo para realizá-la naquele período determinado. <br> <br> Isso aumenta a motivação e a disciplina, tornando mais provável que você realmente inicie e conclua as tarefas no tempo estipulado.</p>'


        document.getElementById('printresultquest2').innerHTML = '<h2 class="result-title">Identifique o <span>problema</span> com precisão!</h2><p class="result-text-dica">Nem tudo se resume à incapacidade de lidar com responsabilidades. Em alguns casos, não é possível concluir uma tarefa devido à falta de tempo, recursos ou até mesmo de capacitação.<br> <br>Portanto, antes de se culpar, tente entender se houve um motivo realmente justo que impediu a realização de algo. Ao identificar o problema, você pode adotar abordagens específicas para solucioná-lo.<br> <br>Se a sobrecarga de tarefas é o problema, a organização e a priorização adequadas podem ajudar a gerenciar a carga de trabalho.<br> <br>Vale ressaltar que identificar o problema também aumenta a conscientização e a autopercepção. Compreendendo os padrões de comportamento procrastinatórios e as causas subjacentes, você se torna mais consciente de seus próprios hábitos e tendências. Isso permite que você monitore seus padrões de pensamento e comportamento e intervenha quando a procrastinação começa a surgir.</p> <br> <br> <h2 class="result-title">Algumas fontes: <br> <br> </h2> <a class="link" target="_blank" href="https://www.napratica.org.br/dicas-como-parar-de-procrastinar/"><i class="fa-solid fa-paperclip"></i>https://www.napratica.org.br/dicas-como-parar-de-procrastinar/</a> <br>  <br> <a class="link" target="_blank" href="https://fia.com.br/blog/procrastinacao/"><i class="fa-solid fa-paperclip"></i>https://fia.com.br/blog/procrastinacao/</a>'

        //var result_quest2 = '<h2 class="result-title">Identifique o <span> problema</span>com precisão</h2><p class="result-text-dica">Nem tudo se resume à incapacidade de lidar com responsabilidades. Em alguns casos, não é possível concluir uma tarefa devido à falta de tempo, recursos ou até mesmo de capacitação.<br> <br> Portanto, antes de se culpar, tente entender se houve um motivo realmente justo que impediu a realização de algo. Ao identificar o problema, você pode adotar abordagens específicas para solucioná-lo. <br> <br>Se a sobrecarga de tarefas é o problema, a organização e a priorização adequadas podem ajudar a gerenciar a carga de trabalho. <br> <br> Vale ressaltar que identificar o problema também aumenta a conscientização e a autopercepção. Compreendendo os padrões de comportamento procrastinatórios e as causas subjacentes, você se torna mais consciente de seus próprios hábitos e tendências. Isso permite que você monitore seus padrões de pensamento e comportamento e intervenha quando a procrastinação começa a surgir.</p> <br> <br> <h2 class="result-title">Algumas fontes: </h2> <a class="social-media-item" target="_blank" href="https://www.napratica.org.br/dicas-como-parar-de-procrastinar/"><i class="fa-solid fa-paperclip"></i>https://www.napratica.org.br/dicas-como-parar-de-procrastinar/</a> <br>  <br> <a class="social-media-item" target="_blank" href="https://fia.com.br/blog/procrastinacao/"><i class="fa-solid fa-paperclip"></i>https://fia.com.br/blog/procrastinacao/</a>'

    } else if (totalScore <= 10) {
        console.log('Chegou aqui', totalScore)
        // Se a pontuação total for 10 ou menos.

        document.getElementById('printtotalscore').innerHTML = '<h1 class="print-result">Nível <span>Baixo</span></h1>'

        document.getElementById('printresultquest').innerHTML = '<h2 class="result-title">Um Olhar sobre o Autocontrole e a Consciência de Tempo</h2><p class="result-text">As pessoas com baixo nível de procrastinação demonstram uma forte capacidade de autorregulação, priorizando tarefas e mantendo o foco no cumprimento dos prazos. Para elas, a procrastinação é uma escolha intencional e não um hábito constante. Esse grupo consegue iniciar tarefas com rapidez, sente satisfação em cumprir compromissos e sabe manter o controle sobre seu tempo.</p> <br> <br> <p class="result-text">Quando surge uma tarefa desafiadora, essas pessoas buscam analisar o que é necessário e agem sem demora, aproveitando a sensação de produtividade e de dever cumprido.</p> <br> <br> <p class="result-text><span>Continue</span> aproveitando esse bom senso de organização e foco! Saber equilibrar o tempo e manter o controle das atividades é um diferencial valioso. Sua dedicação ao que precisa ser feito é inspiradora, e você está no caminho certo para alcançar seus objetivos.</p>'

        var score_info = '<h1 class="print-result">Nível <span>Baixo</span></h1>'
        var result_quest = '<h2 class="result-title">Um Olhar sobre o Autocontrole e a Consciência de Tempo</h2><p class="result-text">As pessoas com baixo nível de procrastinação demonstram uma forte capacidade de autorregulação, priorizando tarefas e mantendo o foco no cumprimento dos prazos. Para elas, a procrastinação é uma escolha intencional e não um hábito constante. Esse grupo consegue iniciar tarefas com rapidez, sente satisfação em cumprir compromissos e sabe manter o controle sobre seu tempo.</p> <br> <br> <p class="result-text">Quando surge uma tarefa desafiadora, essas pessoas buscam analisar o que é necessário e agem sem demora, aproveitando a sensação de produtividade e de dever cumprido.</p> <br> <br> '

        '<p class="result-text><span>Continue</span> aproveitando esse bom senso de organização e foco! Saber equilibrar o tempo e manter o controle das atividades é um diferencial valioso. Sua dedicação ao que precisa ser feito é inspiradora, e você está no caminho certo para alcançar seus objetivos.</p>'
    }
};

// Quando a página carregar, exiba os resultados
window.onload = async function () {
    const results = getInfoBasedOnScore(localStorage.getItem('TotalPontos'));
    const totalPontos = localStorage.getItem('TotalPontos')
    const email = localStorage.getItem('login')
    if (email && totalPontos) {
        const pontosUsuario = {
            email: email,
            totalPontos: totalPontos
        };
        try {
            console.log(pontosUsuario)
            const response = await fetch('http://localhost:3000/api/usuariosPontos', {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify(pontosUsuario)  // Enviando a descrição ao backend

            });

        } catch (error) {
            console.error('Erro ao adicionar tarefa:', error);
        }
    }

}

function limpaLocalStorage() {
    localStorage.setItem('login', '')
}